name: cow-agent

plugins:
  - name: alchemy
    version: 0.8.7
  - name: etherscan
    version: 0.8.4
  - name: foundry
    version: 0.8.7
  - name: solidity
    version: 0.8.5

solidity:
  version: 0.8.25
  import_remapping:
    - '@gnosis.pm/safe-contracts=./contracts/dependencies/@gnosis.pm/safe-contracts'
    - '@gnosis-guild/zodiac=./contracts/dependencies/@gnosis-guild/zodiac'
    - '@openzeppelin/=contracts/dependencies/@openzeppelin/'

dependencies:
  - name: Solady
    github: Vectorized/solady
    ref: v0.1.3
