name: cow-agent

plugins:
  - name: alchemy
    version: 0.8.7
  - name: etherscan
    version: 0.8.4
  - name: foundry
    version: 0.8.7
  - name: solidity
    version: 0.8.5

solidity:
  version: 0.8.27

dependencies:
  - name: Solady
    github: Vectorized/solady
    ref: v0.1.3
  - name: cowprotocol
    github: cowprotocol/contracts
    ref: main
