name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
      - uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - uses: astral-sh/ruff-action@v3

      - uses: ApeWorX/github-action@v3
        with:
          python-version: '3.11'
          ape-version-pin: '0.8.25'
          ape-plugins-list: 'alchemy==0.8.7 etherscan==0.8.4 foundry==0.8.7 solidity==0.8.5'

      - name: Install contract dependencies
        run: ape pm install gh:Vectorized/solady@v0.1.3 --name solady

      - name: Compile contracts
        run: ape compile

      - name: Run tests
        run: ape test -s
