name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
      - uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - uses: astral-sh/ruff-action@v3

      - uses: ApeWorX/github-action@v3
        with:
          ape-version-pin: '0.8.25'

      - name: Run tests
        run: ape test -s
