name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
      - uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - uses: astral-sh/ruff-action@v3

      - uses: ApeWorX/github-action@v3
        with:
          python-version: '3.11'
          ape-version-pin: '0.8.25'

      - name: Install ape plugins
        run: ape plugins install .

      - name: Debug directory structure
        run: |
          echo "Current directory:"
          pwd
          echo "Contents of current directory:"
          ls -la
          echo "Contents of contracts directory:"
          ls -la contracts/
          echo "Installed plugins:"
          ape plugins list

      - name: Install contract dependencies
        run: ape pm install gh:Vectorized/solady --name solady --ref v0.1.3

      - name: Compile contracts
        run: ape compile --include-dependencies -f

      - name: Run tests
        run: ape test -s
